name: Publish gem to rubygems.org

on:
  workflow_dispatch:

jobs:
  release:
    uses: sue445/workflows/.github/workflows/release_gem.yml@main
    with:
      repo-name: sue445/date_discreter
      gem-name:  date_discreter
    permissions:
      contents: write
      id-token: write
